import { NotificationStreamer } from "@/components/NotificationStreamer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NotificationStreamer />
      <div className="flex flex-col min-h-screen">
        <main className="flex-1 map-tile">{children}</main>
      </div>
    </div>
  );
}
