import Header from "@/components/Header";
import LeftMenu from "@/components/LeftMenu";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="mx-auto grid w-full items-start gap-6 md:grid-cols-[180px_1fr] lg:grid-cols-[250px_1fr]">
        <div className="my-4 w-full mx-4">
          <LeftMenu />
        </div>
        <div className="md:w-4/5 w-full max-w-6xl ">
          <main className="flex min-h-screen bg-background">
            <div className="container relative my-4">{children}</div>
          </main>
        </div>
      </div>
    </>
  );
}
